# Custom configs and usual changes to basic configuration file

# HACS custom-sidebar setup
frontend:
  extra_module_url:
    # Use this SPECIFIC file for the YAML configuration version
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js

# HACS favicon setup
favicon:
  title: window title name
  # ./www/favicons
  icon_path: /local/favicons/

# Creating yaml defined custom dashboards
lovelace:
  dashboards:

    # NewDashboard definition
    new-dashboard:    # ID
      mode: yaml
      title: The New Dashboard
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: dashboard-new.yaml
